# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='ecs.packets',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0emessages.proto\x12\x0b\x65\x63s.packets\"\x94\x02\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x13\n\x0bnode_status\x18\x03 \x01(\x04\x12!\n\x04ping\x18\x05 \x01(\x0b\x32\x11.ecs.packets.PingH\x00\x12\'\n\x07inquiry\x18\x06 \x01(\x0b\x32\x14.ecs.packets.InquiryH\x00\x12#\n\x05\x63laim\x18\x07 \x01(\x0b\x32\x12.ecs.packets.ClaimH\x00\x12\'\n\x07meeting\x18\x08 \x01(\x0b\x32\x14.ecs.packets.MeetingH\x00\x12\x30\n\x06resign\x18\t \x01(\x0b\x32\x1e.ecs.packets.ClusterHeadResignH\x00\x42\t\n\x07payload\"\x06\n\x04Ping\"\t\n\x07Inquiry\"\x07\n\x05\x43laim\"\x1c\n\x07Meeting\x12\x11\n\ttablesize\x18\x01 \x01(\x04\"\x13\n\x11\x43lusterHeadResign\"\x08\n\x06Statusb\x06proto3'
)




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='ecs.packets.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ecs.packets.Message.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ecs.packets.Message.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_status', full_name='ecs.packets.Message.node_status', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ping', full_name='ecs.packets.Message.ping', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inquiry', full_name='ecs.packets.Message.inquiry', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='claim', full_name='ecs.packets.Message.claim', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meeting', full_name='ecs.packets.Message.meeting', index=6,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resign', full_name='ecs.packets.Message.resign', index=7,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='ecs.packets.Message.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=32,
  serialized_end=308,
)


_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='ecs.packets.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=316,
)


_INQUIRY = _descriptor.Descriptor(
  name='Inquiry',
  full_name='ecs.packets.Inquiry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=327,
)


_CLAIM = _descriptor.Descriptor(
  name='Claim',
  full_name='ecs.packets.Claim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=336,
)


_MEETING = _descriptor.Descriptor(
  name='Meeting',
  full_name='ecs.packets.Meeting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tablesize', full_name='ecs.packets.Meeting.tablesize', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=366,
)


_CLUSTERHEADRESIGN = _descriptor.Descriptor(
  name='ClusterHeadResign',
  full_name='ecs.packets.ClusterHeadResign',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=387,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='ecs.packets.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=397,
)

_MESSAGE.fields_by_name['ping'].message_type = _PING
_MESSAGE.fields_by_name['inquiry'].message_type = _INQUIRY
_MESSAGE.fields_by_name['claim'].message_type = _CLAIM
_MESSAGE.fields_by_name['meeting'].message_type = _MEETING
_MESSAGE.fields_by_name['resign'].message_type = _CLUSTERHEADRESIGN
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['ping'])
_MESSAGE.fields_by_name['ping'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['inquiry'])
_MESSAGE.fields_by_name['inquiry'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['claim'])
_MESSAGE.fields_by_name['claim'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['meeting'])
_MESSAGE.fields_by_name['meeting'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['resign'])
_MESSAGE.fields_by_name['resign'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['Inquiry'] = _INQUIRY
DESCRIPTOR.message_types_by_name['Claim'] = _CLAIM
DESCRIPTOR.message_types_by_name['Meeting'] = _MEETING
DESCRIPTOR.message_types_by_name['ClusterHeadResign'] = _CLUSTERHEADRESIGN
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:ecs.packets.Message)
  })
_sym_db.RegisterMessage(Message)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), {
  'DESCRIPTOR' : _PING,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:ecs.packets.Ping)
  })
_sym_db.RegisterMessage(Ping)

Inquiry = _reflection.GeneratedProtocolMessageType('Inquiry', (_message.Message,), {
  'DESCRIPTOR' : _INQUIRY,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:ecs.packets.Inquiry)
  })
_sym_db.RegisterMessage(Inquiry)

Claim = _reflection.GeneratedProtocolMessageType('Claim', (_message.Message,), {
  'DESCRIPTOR' : _CLAIM,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:ecs.packets.Claim)
  })
_sym_db.RegisterMessage(Claim)

Meeting = _reflection.GeneratedProtocolMessageType('Meeting', (_message.Message,), {
  'DESCRIPTOR' : _MEETING,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:ecs.packets.Meeting)
  })
_sym_db.RegisterMessage(Meeting)

ClusterHeadResign = _reflection.GeneratedProtocolMessageType('ClusterHeadResign', (_message.Message,), {
  'DESCRIPTOR' : _CLUSTERHEADRESIGN,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:ecs.packets.ClusterHeadResign)
  })
_sym_db.RegisterMessage(ClusterHeadResign)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:ecs.packets.Status)
  })
_sym_db.RegisterMessage(Status)


# @@protoc_insertion_point(module_scope)
