# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('ecs-clustering-example', ['ecs-clustering', 'netanim'])
    obj.source = [
        'nsutil.cc',
        'ecs-clustering-example.cc',
        'simulation-params.cc',
        'simulation-area.cc'
        ]
