# Run build-ns3
name: build-ns3

on: [push, pull_request]

jobs:
  build-on-ns3:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ns3 build
      uses: marshallasch/ns3-action@34.1
      with:
        location: 'contrib'
        pre_run: 'pre.sh'
        sim_name: 'ecs-clustering-example'
        sim_args: '--runTime=120'
